### ISSUE TITLE
New homekit BCM500DS-TYW Tuya motor codes

### ISSUE THREAD

**Issue by Tigerstrength** [iphong/esphome-tuya-curtain#4]
Hi,

I have the newest version with homekit option. There is no ESP anymore inside, but what looks like a custom Tuya chip. I did not try to flash this onboard chip, but I doubt wether that would work.

So I got a ESP8266 of the shelf and programmed it with this ESPHome code. Sadly it not work, I cut the power to the Tuya onboard Wifi chip and used the TX en RX pin of that wifi chip (note, dont use the pin header with Tx Rx writing, it is a different interface) to connect the UART of the ESP to.

In the end I ended up sniffing al the traffic on that interface when te motor was connected to the Tuya app and came up with these codes below (decimal, not hex).

Surely everthing can be more clean coded, but these are the working values I would like to share to others as a start to get the motor working. Works for days now and looks very stable.

```
              if (call.get_stop()) { //stop
			crc = 0;
			writeByte(85);
			writeByte(170);
			writeByte(0);
			writeByte(6);
			writeByte(0);
			writeByte(5);
			writeByte(1);
			writeByte(4);
			writeByte(0);
			writeByte(1);
			writeByte(1);
			writeByte(17);
		}
```
	```
	if (call.get_position().has_value()) {
			crc = 0;
			uint8_t pos = *call.get_position() * 100.0f;
			if (pos == 100) { //close
				writeByte(85);
				writeByte(170);
				writeByte(0);
				writeByte(6);
				writeByte(0);
				writeByte(5);
				writeByte(1);
				writeByte(4);
				writeByte(0);
				writeByte(1);
				writeByte(0);
				writeByte(16);
				
			} else if (pos == 0) {  //open
				writeByte(85);
				writeByte(170);
				writeByte(0);
				writeByte(6);
				writeByte(0);
				writeByte(5);
				writeByte(1);
				writeByte(4);
				writeByte(0);
				writeByte(1);
				writeByte(2);
				writeByte(18);
			} else { //position
				writeByte(85);
				writeByte(170);
				writeByte(0);
				writeByte(6);
				writeByte(0);
				writeByte(8);
				writeByte(2);
				writeByte(2);
				writeByte(0);
				writeByte(4);
				writeByte(0);
				writeByte(0);
				writeByte(0);
				writeByte(pos);
				writeByte(crc);
			}
		}
	}
```
`	void setMotorNormal() {
		writeByte(85);
		writeByte(170);
		writeByte(0);
		writeByte(6);
		writeByte(0);
		writeByte(5);
		writeByte(5);
		writeByte(4);
		writeByte(0);
		writeByte(1);
		writeByte(1);
		writeByte(21);
	}

	void setMotorReversed() {
		writeByte(85);
		writeByte(170);
		writeByte(0);
		writeByte(6);
		writeByte(0);
		writeByte(5);
		writeByte(5);
		writeByte(4);
		writeByte(0);
		writeByte(1);
		writeByte(1);
		writeByte(20);
	}`

//And the position I read from (only basic info at the start and the end of a run by filtering on buffer[10]==67 only as the rest required me too much time to find out and I never need the position during motor running.

if (sum == crc and buffer[10] == 67 ) { 
 position =  buffer[17] / 100.0f;

**Comment by Tigerstrength** [comment]
Update: it is now also possible to control these motors with a custom ESP8266/32 with ESPHome using the default Tuya component with this yaml:
```

esphome:
  name: choose your name

esp8266:
  board: d1_mini  #I soldered a d1_mini esp board in the motor

wifi:
  ssid: "x"   #fill with own credentials
  password: "x"  #fill with own credentials
  manual_ip:
    static_ip: 192.168.x.x #fill with own credentials
    gateway: 192.168.x.x   #fill with own credentials
    subnet: 255.255.x.x    #fill with own credentials

logger:
  baud_rate: 0

api:
  reboot_timeout: 24h

ota:
  platform: esphome

uart:
  - id: com_1
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 9600

tuya:

cover:
  - platform: "tuya"
    device_class: curtain
    name: "Curtain"
    control_datapoint: 1
    position_datapoint: 2
```
