### ISSUE TITLE
Custom components have been removed in esphome

### ISSUE THREAD

**Issue by Zouljiin** [iphong/esphome-tuya-curtain#5]
this section no longer works and needs to be converted to external_components
https://esphome.io/guides/contributing#a-note-about-custom-components

i'm currently trying to figure it out, but its out of my knowledge set at the moment.

cover:
  - platform: custom
    lambda: |-
      auto curtain = new CustomCurtain();
      App.register_component(curtain);
      return {curtain};
    covers:
      - name: Curtain
        device_class: blind

custom_component:
  - lambda: |-
      return { new CustomAPI() };

**Comment by ceaswaran** [comment]
+1
I am also struck here
@iphong  Please help

**Comment by GraceGRD** [comment]
Esphome have a component [tuya](https://esphome.io/components/cover/tuya.html) which you can use for the cover integration.

**Comment by Zouljiin** [comment]
I have it implemented but its not fully functional. The controls are wrong
and it's not remembering its state through reboots. I have an issue open
with them too.

**Comment by GraceGRD** [comment]
My Zemismart slide curtain is driven by the ZZM79E-DT motor and uses a TYWE1S wifi module.
If you have the same motor/wifi module this configuration should work:

``` yaml
# Implementation
uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Create a cover using the datapoint from above
cover:
  - platform: tuya
    name: "None"
    device_class: curtain
    control_datapoint: 1
    direction_datapoint: 5
    position_datapoint: 2
    position_report_datapoint: 3
    invert_position: true
    restore_mode: RESTORE
```

When using the configuration above please double-check your uart configuration. I made a custom PCB that replaces the TYWE1S wifi module to be able to convert the curtain back to original firmware.

I can imagine that the controls could be a little bit different if you use a different motor... Remembering position through reboots works fine with option `restore_mode: RESTORE`.

Hope this will help for you.
